name: PowerShell Module CI

on:
  push:
    branches:
      - main
    tags:
      - "v*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    name: Test and Publish PowerShell Module

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser
          Invoke-ScriptAnalyzer -Path ./ -Recurse

      - name: Validate Module Manifest
        shell: pwsh
        run: |
          Test-ModuleManifest -Path ./Start-AdConDeltaSync.psd1

      - name: Trust PSGallery
        shell: pwsh
        run: |
          Set-PSRepository -Name PSGallery -InstallationPolicy Trusted

      - name: Prepare module for publishing
        shell: pwsh
        run: |
          $publishPath = "$env:TEMP\Start-AdConDeltaSync"
          New-Item -ItemType Directory -Path $publishPath -Force | Out-Null
          Copy-Item -Path .\Start-AdConDeltaSync.psd1, .\Start-AdConDeltaSync.psm1, .\config.sample.ini, README.md -Destination $publishPath

      - name: Publish to PowerShell Gallery
        if: startsWith(github.ref, 'refs/tags/v')
        shell: pwsh
        env:
          PSGalleryApiKey: ${{ secrets.PSGALLERY_API_KEY }}
        run: |
          Publish-Module -path ./ -NuGetApiKey $env:PSGalleryApiKey
